### ISSUE TITLE
Media Kit

### ISSUE THREAD

**Issue by annabhill** [Emery-Ventures/icrunchdata#220]
Add pages for Influential Marketing and Rates.

**Comment by rtemery** [comment]
Replace a few device mockups -- try PS method.

**Comment by rtemery** [comment]
Left to do:
- Copy for email marketing and influential marketing
- Hi-res device mockups for flipboard and curated sourcing

**Comment by rtemery** [comment]
Left to do -
Need a screencapture with the (new) cover of digital magazine.

**Comment by rtemery** [comment]
Remaining hi-res images are on flash drive for Content Distribution and Curated Sourcing

**Comment by annabhill** [comment]
Done!
