### ISSUE TITLE
Questions

### ISSUE THREAD

**Issue by annabhill** [Emery-Ventures/icrunchdata#231]
- [x] Logo: upload SVG file (getting error)
A: Not Possible
- [x] Favicon: dimensions?
A: 16px x 16px
- [x] Customize Theme > Navigation Menu: Drag and drop isn't working in Chrome browser. Currently unable to create dropdown menu
A: Works in IE (chrome bug)
- [x] Storage: Do we have a limit? 
A: No limit.
- [x] Wysiwyg editor: Ability to add nofollow links
A:  Have to use source code rel="nofollow" (But may add this to the roadmap)
- [x] Post a Job process: Agency umbrella account vs individual? How would they post company name/website in a job posting?
A: Only individual accounts per employer
- [x] Employer Account or Post a Job process setup: Can employers add social media fields/icons?
A: Unable to at this time. Must be added to About section. (She will add to roadmap)
- [x] Employer Account: Are cc stored on file for future use?
A: Only stored for recurring products.
- [x] Recurring subscriptions: Can be used with Stripe or PayPal Express payment methods only. What about Authorize.net ARB?
A:  Not at this time, but will add this to roadmap.
- [x] Contact: Where to control form fields and email recipients?
A: No custom fields at this time. Recipient is set under 'settings > admin'
- [x] Job alert signup: Can user customize by Keyword and Location
A: It's a generic one from homepage. Intelligent one from the job search.
- [x] Blog: Show social share count
A: Not presently. Will consider adding to roadmap.
- [x] XML inbound: Need to understand url vs file method
A: URL is required (not one-off files)
- [x] 301 Redirects: How to input?
A: Not possible, javascript method only

**Comment by rtemery** [comment]
Done.
