### ISSUE TITLE
The Job Network Setup

### ISSUE THREAD

**Issue by annabhill** [Emery-Ventures/icrunchdata#233]

**Comment by rtemery** [comment]
Notes from call:

PURCHASE SIDE
Traffic Network = $0.20to 0.30 CPC
Application Network = $3.00 to 5.00

SELL SIDE
$0.15 to 0.18 CPC (Flat rate)
$1.15 to 2.50 CPA (Flat rate)
Better monitization for variable rates but needs to be implemented

PURCHASE CANDIDATES
$0.70 to .0.75 / candidate
sent via email in real-time -- but manual.

**Comment by rtemery** [comment]
When we set up our profile with them -- reminder to create a [description the premier tech job board for data science, analytics and technology professionals.](https://icrunchdata.com/tech-job-board/)

**Comment by rtemery** [comment]
Left to do:
- [ ] Payment routing
- [ ] Delete inactive feed
- [ ] Confirm CPC action
- [ ] Block competitors
- [ ] Check to see if orphan employer profiles are created

**Comment by rtemery** [comment]
We need to create a spreadsheet with:
- [ ] Keywords matching title
- [ ] Optout Advertiser names

**Comment by rtemery** [comment]
Done.
