### ISSUE TITLE
Job Advertising Guidelines

### ISSUE THREAD

**Issue by rtemery** [Emery-Ventures/icrunchdata#239]
Revise job posting fields to match new schema

**Comment by rtemery** [comment]
check language around real vs fake jobs
check language around real location (not anywhere)
check language around expires in 365 days from date of purchase (might be in Terms)

**Comment by rtemery** [comment]
This page is specific to employers [posting jobs on icrunchdata tech job board for technology and data professionals](https://icrunchdata.com/job-advertising-guidelines/)

**Comment by annabhill** [comment]
Done 🥇
