### ISSUE TITLE
Display Ads

### ISSUE THREAD

**Issue by annabhill** [Emery-Ventures/icrunchdata#240]
- [x] Set ad unit placements
- [x] Fix mobile responsive issue
- [x] Fix close button issue (homepage)
- [x] Interstitial ad needs user limit setting
- [x] Modify settings to exclude pages (negative keywords; ie 'job description')
- [x] Schedule task/calendar reminder to revisit in August

**Comment by annabhill** [comment]
Add and test on mobile

**Comment by rtemery** [comment]
Welcome ad background.

**Comment by annabhill** [comment]
- [ ] Fix mobile responsive issue
- [ ] Fix close button issue

**Comment by rtemery** [comment]
We have our solution for this. I'll move to Post Live

**Comment by annabhill** [comment]
Done.
