### ISSUE TITLE
Questions Round 2

### ISSUE THREAD

**Issue by annabhill** [Emery-Ventures/icrunchdata#246]
- [x] Job Seeker and Employer Account meta: Welcome to the employer account dashboard for icrunchdata. Here you can manage your jobs and post new ones, get support and manage your account.
A: n/a since these are logged in accounts and not indexed.
- [x] Jobs meta: Welcome job seekers to our award-winning tech job board platform that's lightweight and content-forward so you can easily apply to jobs from both desktop.
A:  No access
- [x] Blog meta: News and hot topics in tech, data science, analytics, IoT and cybersecurity by icrunchdata. Sign up for our email newsletter today to get scorching content.
A:  Only available for individual blog posts
- [x] Post a Job meta: Post it jobs, tech jobs, analytics jobs, data jobs, cybersecurity jobs. icrunchdata is an award-winning job board platform. Post your jobs today and start...
A: No access to update
-----------------------------------
- [x] What icons can we use for Flipboard and RSS or external link?
A: Have ticket open on this.
- [x] Confirm primary url will be https:// site-wide and no-www
A: Yes
- [x] For Job Import by XML, is this mapped to a unique employer account?
A: Yes can be set up unique to each employer account
- [x] Backups?
A: Daily backups - can do a restore upon request within 1 week window. Backups older than 1 week re not available.

**Comment by rtemery** [comment]
Need to update meta data on [the premier tech job board for data science, analytics and everything technology jobs.](https://icrunchdata.com/tech-job-board/)

**Comment by rtemery** [comment]
Also, meta data on the homepage [the premier IT job board for data science, analytics and everything technology jobs.](https://icrunchdata.com/it-jobs/)
