### ISSUE TITLE
Blog Content Migration

### ISSUE THREAD

**Issue by rtemery** [Emery-Ventures/icrunchdata#248]
Working on a system for this.

**Comment by rtemery** [comment]
Talking to V tonight.

**Comment by rtemery** [comment]
Left to do:
- [ ] URL spreadsheet
- [ ] Featured image
- [ ] Embedded images (if applicable)
- [ ] Credit box
- [ ] Possibly add share count
- [ ] Final approval of formatting

**Comment by annabhill** [comment]
Done. Share count display to be considered at a later date.
