### ISSUE TITLE
DB Cleanup

### ISSUE THREAD

**Issue by rtemery** [Emery-Ventures/icrunchdata#276]
The Job Network -- I want all jobs (first) deleted THEN all employers (second) deleted that are from The Job Network. That gives us a clean slate until I can get the ROOT source feed clean.

I'm submitting a spreadsheet of title keywords and optout advertisers.

**Comment by rtemery** [comment]
I've deactivated the plugin for this API, and will reactivate once we have confirmation from their side we are clean.

**Comment by rtemery** [comment]
Just learned that if we delete an employer the jobs associated are also deleted. So that seems easier.

**Comment by annabhill** [comment]
Done - The Job Network employers and jobs are deleted.

**Comment by rtemery** [comment]
Do you know if we needed to keep (1) by default for the plugin to work?  I'll chat and see.

**Comment by rtemery** [comment]
Also, I went through 9000+ jobs to create a title keyword list and optout list. Emailed that to them already.

**Comment by annabhill** [comment]
Ok. I did not know if the 'test' Job Network employer profiles needed to remain, so I did not delete the (2) that exist.

**Comment by rtemery** [comment]
Done - The Job Network is live with Distribution :1st_place_medal:
